In [ ]:
!pip install tensorflow

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 572.6/572.6 MB 760.7 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 143.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 102.2 MB/s eta 0:00:00
  Attempting uninstall: h5py
    Found existing installation: h5py 3.16.0
    Uninstalling h5py-3.16.0:
      Successfully uninstalled h5py-3.16.0


In [ ]:
import tensorflow as tf

/usr/local/lib/python3.12/dist-packages/jax/_src/cloud_tpu_init.py:86: UserWarning: Transparent hugepages are not enabled. TPU runtime startup and shutdown time should be significantly improved on TPU v5e and newer. If not already set, you may need to enable transparent hugepages in your VM image (sudo sh -c "echo always > /sys/kernel/mm/transparent_hugepage/enabled")
  warnings.warn(


In [ ]:
import tensorflow as tf
tf.random.set_seed(42)

t1 = tf.constant([1,2,3,4,5])
t2 = tf.random.normal(shape=(3,3))
v1 = tf.Variable(tf.zeros(shape=(2,4)))

for name, t in [('Tensor 1', t1), ('Tensor 2', t2), ('Variable', v1)]:
  print(f'{name} shape:{t.shape} dtype:{t.dtype.name} rank:{tf.rank(t).numpy()}')

Tensor 1 shape:(5,) dtype:int32 rank:1
Tensor 2 shape:(3, 3) dtype:float32 rank:2
Variable shape:(2, 4) dtype:float32 rank:2


In [ ]:
import tensorflow as tf
tf.random.set_seed(42)

A = tf.random.normal(shape=(2,3))
B = tf.random.normal(shape=(2,3))
print('A:', A)
print('B:', B)
print(f'Add : ',tf.add(A,B))
print(f'Multiply : ',tf.matmul(A,tf.transpose(B)))
print(f'Mean of A : ',tf.reduce_mean(A))
print(f'Mean of B: ',tf.reduce_mean(B))
print('A + B shape: ',tf.add(A,B).shape)
print('A * B shape: ',tf.matmul(A,tf.transpose(B)).shape)
print('Mean of A: ',tf.reduce_mean(A).numpy())
print('Mean of B: ',tf.reduce_mean(B).numpy())

A: tf.Tensor(
[[ 0.3274685 -0.8426258  0.3194337]
 [-1.4075519 -2.3880599 -1.0392479]], shape=(2, 3), dtype=float32)
B: tf.Tensor(
[[ 0.08422458 -0.86090374  0.37812304]
 [-0.00519627 -0.49453196  0.6178192 ]], shape=(2, 3), dtype=float32)
Add :  tf.Tensor(
[[ 0.4116931  -1.7035296   0.69755673]
 [-1.4127482  -2.8825917  -0.42142868]], shape=(2, 3), dtype=float32)
Multiply :  tf.Tensor(
[[0.87378585 0.61235607]
 [1.5443757  0.5462186 ]], shape=(2, 2), dtype=float32)
Mean of A :  tf.Tensor(-0.8384306, shape=(), dtype=float32)
Mean of B:  tf.Tensor(-0.046744186, shape=(), dtype=float32)
A + B shape:  (2, 3)
A * B shape:  (2, 2)
Mean of A:  -0.8384306
Mean of B:  -0.046744186


In [ ]:
import tensorflow as tf
from tensorflow import keras
model = keras.Sequential([keras.layers.Dense(128, activation='relu', input_shape=(784,)),
                          keras.layers.Dense(64, activation='relu'),
                          keras.layers.Dense(10, activation='softmax')])
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 128)            │       100,480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 109,386 (427.29 KB)

 Trainable params: 109,386 (427.29 KB)

 Non-trainable params: 0 (0.00 B)